#!/usr/bin/env bash
# tasks/07-write-restore.sh
# Generate a self-contained restore.sh inside the service output folder.
# Usage: 07-write-restore.sh <service_dir> <dockge_stacks_dir>
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../../lib/common.sh"

SERVICE_DIR="${1:?Usage: $0 <service_dir> <dockge_stacks_dir>}"
DOCKGE_STACKS_DIR="${2:-/opt/stacks}"

META_FILE="$SERVICE_DIR/.stack-meta"
[[ -f "$META_FILE" ]] || { warn "No .stack-meta in $SERVICE_DIR — skipping restore generation"; exit 0; }

SOURCE_STACK="$(grep '^SOURCE_STACK=' "$META_FILE" | cut -d= -f2-)"
SOURCE_FILE="$(grep '^SOURCE_FILE='  "$META_FILE" | cut -d= -f2-)"
SERVICE_NAME="$(grep '^SERVICE_NAME=' "$META_FILE" | cut -d= -f2-)"

RESTORE_SCRIPT="$SERVICE_DIR/restore.sh"

cat > "$RESTORE_SCRIPT" << RESTORE_EOF
#!/usr/bin/env bash
# restore.sh — generated by phase-1 backup
# Restores ${SERVICE_NAME} back into the ${SOURCE_STACK} Dockge stack.
# Run this script from inside its own folder.
set -euo pipefail

SELF_DIR="\$(cd "\$(dirname "\$0")" && pwd)"
SERVICE_COMPOSE="\$SELF_DIR/docker-compose.yml"
SERVICE_ENV="\$SELF_DIR/.env"

DOCKGE_STACKS_DIR="\${DOCKGE_STACKS_DIR:-${DOCKGE_STACKS_DIR}}"
STACK_DIR="\$DOCKGE_STACKS_DIR/${SOURCE_STACK}"
STACK_COMPOSE="\$STACK_DIR/compose.yaml"
STACK_ENV="\$STACK_DIR/.env"

SERVICE_NAME="${SERVICE_NAME}"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Restoring: \$SERVICE_NAME → \$STACK_DIR"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

command -v yq &>/dev/null || { echo "❌ yq is required but not installed."; exit 1; }

# ── STEP 1 — Create stack directory ─────────────────────────────────────────
mkdir -p "\$STACK_DIR"
[[ ! -f "\$STACK_COMPOSE" ]] && echo "services:" > "\$STACK_COMPOSE" && echo "  Created new compose.yaml"

# ── STEP 2 — Merge service block ────────────────────────────────────────────
existing="\$(yq ".services | has(\"\$SERVICE_NAME\")" "\$STACK_COMPOSE" 2>/dev/null || echo "false")"
if [[ "\$existing" == "true" ]]; then
  echo "  ⚠️  Service '\$SERVICE_NAME' already exists — skipping"
else
  echo "  ✔ Merging service: \$SERVICE_NAME"
  yq -i ".services.\"\${SERVICE_NAME}\" = load(\"\$SERVICE_COMPOSE\").services.\"\${SERVICE_NAME}\"" "\$STACK_COMPOSE"
fi

# ── STEP 3 — Merge top-level networks ───────────────────────────────────────
networks="\$(yq '.networks | keys | .[]' "\$SERVICE_COMPOSE" 2>/dev/null || true)"
if [[ -n "\$networks" ]]; then
  while IFS= read -r net; do
    [[ -z "\$net" || "\$net" == "null" ]] && continue
    net_exists="\$(yq ".networks | has(\"\$net\")" "\$STACK_COMPOSE" 2>/dev/null || echo "false")"
    if [[ "\$net_exists" == "true" ]]; then
      echo "  ⚠️  Network '\$net' already exists — skipping"
    else
      echo "  ✔ Merging network: \$net"
      yq -i ".networks.\"\$net\" = load(\"\$SERVICE_COMPOSE\").networks.\"\$net\"" "\$STACK_COMPOSE"
    fi
  done <<< "\$networks"
fi

# ── STEP 4 — Merge top-level volumes ────────────────────────────────────────
volumes="\$(yq '.volumes | keys | .[]' "\$SERVICE_COMPOSE" 2>/dev/null || true)"
if [[ -n "\$volumes" ]]; then
  while IFS= read -r vol; do
    [[ -z "\$vol" || "\$vol" == "null" ]] && continue
    vol_exists="\$(yq ".volumes | has(\"\$vol\")" "\$STACK_COMPOSE" 2>/dev/null || echo "false")"
    if [[ "\$vol_exists" == "true" ]]; then
      echo "  ⚠️  Volume '\$vol' already exists — skipping"
    else
      echo "  ✔ Merging volume: \$vol"
      yq -i ".volumes.\"\$vol\" = load(\"\$SERVICE_COMPOSE\").volumes.\"\$vol\"" "\$STACK_COMPOSE"
    fi
  done <<< "\$volumes"
fi

# ── STEP 5 — Merge .env variables ───────────────────────────────────────────
if [[ -f "\$SERVICE_ENV" ]]; then
  touch "\$STACK_ENV"
  while IFS= read -r line || [[ -n "\$line" ]]; do
    [[ -z "\$line" || "\$line" =~ ^[[:space:]]*# ]] && continue
    key="\$(echo "\$line" | cut -d= -f1 | sed 's/^[[:space:]]*//;s/[[:space:]]*\$//')"
    [[ -z "\$key" ]] && continue
    if grep -qE "^[[:space:]]*\${key}[[:space:]]*=" "\$STACK_ENV" 2>/dev/null; then
      echo "  ⚠️  Env var '\$key' already exists — skipping"
    else
      echo "  ✔ Appending env var: \$key"
      echo "\$line" >> "\$STACK_ENV"
    fi
  done < "\$SERVICE_ENV"
fi

# ── STEP 6 — Restore bind-mount data ────────────────────────────────────────
# Load the restored stack env so vars like \$CONTAINERS_ROOT resolve
if [[ -f "\$STACK_ENV" ]]; then
  set -o allexport
  source "\$STACK_ENV" 2>/dev/null || true
  set +o allexport
fi

echo "  Restoring bind-mount data..."

yq '.services.*.volumes[]' "\$SERVICE_COMPOSE" 2>/dev/null | while IFS= read -r raw_volume; do
  [[ -z "\$raw_volume" ]] && continue

  container_path="\$(echo "\$raw_volume" | cut -d':' -f2)"
  mount_name="\$(basename "\$container_path")"
  raw_host="\$(echo "\$raw_volume" | cut -d':' -f1)"
  host_path="\$(eval echo "\$raw_host" 2>/dev/null || echo "\$raw_host")"

  # Skip named volumes
  if [[ ! "\$host_path" =~ ^[/\\.] ]] && [[ ! "\$host_path" =~ ^~ ]]; then
    continue
  fi

  # Find local backup folder (mount_name or SERVICE_NAME__mount_name)
  local_dir="\$SELF_DIR/\$mount_name"
  [[ ! -d "\$local_dir" ]] && local_dir="\$SELF_DIR/\${SERVICE_NAME}__\${mount_name}"
  if [[ ! -d "\$local_dir" ]]; then
    echo "  ⚠️  No backup data for '\$mount_name' — skipping"
    continue
  fi

  if [[ ! "\$host_path" =~ ^/ ]]; then
    echo "  ⚠️  Could not resolve host path for '\$raw_host' — skipping"
    continue
  fi

  echo "  ✔ Restoring: \$local_dir → \$host_path"
  mkdir -p "\$host_path"
  cp -rf "\$local_dir/." "\$host_path/" 2>/dev/null || \
    sudo cp -rf "\$local_dir/." "\$host_path/" 2>/dev/null || \
    echo "  ⚠️  Could not restore \$local_dir → \$host_path"

done

echo ""
echo "✅ Restore complete: \$SERVICE_NAME"
echo "   Compose : \$STACK_COMPOSE"
echo "   Env     : \$STACK_ENV"
echo ""
echo "   Start with: cd \$STACK_DIR && docker compose up -d"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
RESTORE_EOF

chmod +x "$RESTORE_SCRIPT"
ok "Generated restore.sh for: $(basename "$SERVICE_DIR")"