#!/usr/bin/env bash
# tasks/04-write-manifest.sh
# Write a manifest.env file into the backup directory, summarising every key
# piece of information about this backup run.
#
# Inputs (env):
#   STATE_FILE  — state file accumulated by tasks 01–03
#
# Outputs:
#   $BACKUP_DIR/manifest.env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../../../lib/common.sh"

# ── Source state ──────────────────────────────────────────────────────────────
STATE_FILE="${STATE_FILE:?STATE_FILE must be set by the orchestrator}"
[[ -f "$STATE_FILE" ]] || die "Detection state not found: $STATE_FILE"
# shellcheck source=/dev/null
source "$STATE_FILE"

: "${BACKUP_DIR:?Missing BACKUP_DIR in state file}"
: "${IMMICH_COMPOSE_FILE:?}"
: "${IMMICH_ENV_FILE:?}"
: "${IMMICH_SERVICE:?}"
: "${POSTGRES_SERVICE:?}"

RUN_ID="${RUN_ID:-$(date -u +%Y%m%dT%H%M%SZ)}"   # ← soft default, not a hard require

manifest="$BACKUP_DIR/manifest.env"

bold "📋 Writing Manifest"
line

cat > "$manifest" << EOF
# Immich backup manifest — generated by phase-2
# Do not edit manually; used by 05-consolidate.sh and future restore tooling.

RUN_ID=$RUN_ID
BACKUP_DIR=$BACKUP_DIR
BACKED_UP_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

IMMICH_COMPOSE_FILE=$IMMICH_COMPOSE_FILE
IMMICH_ENV_FILE=$IMMICH_ENV_FILE
IMMICH_SERVICE=$IMMICH_SERVICE
POSTGRES_SERVICE=$POSTGRES_SERVICE

UPLOAD_SOURCE=${UPLOAD_SOURCE:-unknown}
DATABASE_USED=${DATABASE_USED:-unknown}
DB_DUMP_FILE=${DB_DUMP_FILE:-$BACKUP_DIR/immich_db.sql.gz}
DB_DUMP_SIZE=${DB_DUMP_SIZE:-unknown}
LIBRARY_SIZE=${LIBRARY_SIZE:-unknown}
EOF

ok "Manifest saved: $manifest"
info "  RUN_ID           : $RUN_ID"
info "  Immich service   : $IMMICH_SERVICE"
info "  Postgres service : $POSTGRES_SERVICE"
info "  Database used    : ${DATABASE_USED:-unknown}"
info "  DB dump size     : ${DB_DUMP_SIZE:-unknown}"
info "  Library size     : ${LIBRARY_SIZE:-unknown}"
