#!/usr/bin/env bash
# phase-2/tasks/05-write-restore.sh
# Generates a master restore.sh inside the consolidated immich/ output folder.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../../../lib/common.sh"

# shellcheck source=/dev/null
source "$STATE_FILE"

IMMICH_SERVICE="${IMMICH_SERVICE:?}"
POSTGRES_SERVICE="${POSTGRES_SERVICE:?}"
IMMICH_COMPOSE_FILE="${IMMICH_COMPOSE_FILE:?Missing IMMICH_COMPOSE_FILE in state file}"
IMMICH_ENV_FILE="${IMMICH_ENV_FILE:?Missing IMMICH_ENV_FILE in state file}"
DOCKGE_STACKS_DIR="${DOCKGE_STACKS_DIR:-/opt/stacks}"
IMMICH_OUT_NAME="${IMMICH_OUT_NAME:-immich}"
BACKED_UP_AT="${BACKED_UP_AT:-unknown}"

CONSOLIDATED_DIR="$CENTRAL_BACKUP_DIR/split_stacks/$IMMICH_OUT_NAME"
DB_SERVICE_DIR="$CONSOLIDATED_DIR/$POSTGRES_SERVICE"
DBDUMPFILE="$DB_SERVICE_DIR/immich_db.sql.gz"

[[ -d "$CONSOLIDATED_DIR" ]] || die "Consolidated dir not found: $CONSOLIDATED_DIR — run 04-consolidate.sh first"
[[ -f "$DBDUMPFILE" ]]       || die "Database dump not found: $DBDUMPFILE — run 02-backup-database.sh first"

RESTORE_SCRIPT="$CONSOLIDATED_DIR/restore.sh"

bold "✍  Writing Immich master restore.sh"
line

mapfile -t SERVICE_RESTORE_SCRIPTS < <(
  find "$CONSOLIDATED_DIR" -mindepth 2 -maxdepth 2 -name restore.sh | sort
)

SERVICE_RESTORE_LINES=""
for s in "${SERVICE_RESTORE_SCRIPTS[@]}"; do
  rel="${s#"$CONSOLIDATED_DIR"/}"
  SERVICE_RESTORE_LINES+="  run_restore \"\$DIR/$rel\""$'\n'
done

# ── Write the generated restore.sh ────────────────────────────────────────────
# IMPORTANT: Variables that must expand NOW (at generation time) use ${VAR}.
# Variables that must expand LATER (at restore time)  use \${VAR}.
# The heredoc delimiter is quoted ('RESTOREEOF') so the shell does NOT
# expand anything inside — we control expansion manually via the above rule.

cat > "$RESTORE_SCRIPT" << 'RESTOREEOF_MARKER'
#!/usr/bin/env bash
# Immich Full Restore — generated by phase-2/tasks/05-write-restore.sh
set -euo pipefail

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
DIR="$SELF_DIR"

RED='\e[31m'; GREEN='\e[32m'; YELLOW='\e[33m'; BLUE='\e[36m'; BOLD='\e[1m'; RESET='\e[0m'
line()  { echo -e "${BLUE}------------------------------------------------------------${RESET}"; }
info()  { echo -e "${BLUE}  $*${RESET}"; }
ok()    { echo -e "${GREEN}✅ $*${RESET}"; }
warn()  { echo -e "${YELLOW}⚠️  $*${RESET}"; }
die()   { echo -e "${RED}❌ $*${RESET}" >&2; exit 1; }
bold()  { echo -e "${BOLD}$*${RESET}"; }
RESTOREEOF_MARKER

# Now append the baked-in values — this section IS expanded by the shell
cat >> "$RESTORE_SCRIPT" << RESTOREEOF
DOCKGE_STACKS_DIR="${DOCKGE_STACKS_DIR}"
POSTGRES_SERVICE="${POSTGRES_SERVICE}"
IMMICH_SERVICE="${IMMICH_SERVICE}"
BACKED_UP_AT="${BACKED_UP_AT}"
RESTOREEOF

# Rest of the script — no variable expansion needed from generator context
cat >> "$RESTORE_SCRIPT" << 'RESTOREEOF_MARKER'

STACK_DIR="$DOCKGE_STACKS_DIR/immich"
STACK_COMPOSE="$STACK_DIR/compose.yaml"
STACK_ENV="$STACK_DIR/.env"
DUMPFILE="$DIR/${POSTGRES_SERVICE}/immich_db.sql.gz"

# ── Privilege escalation — ask for sudo only if needed ───────────────────────
SUDO=""
if [[ "$(id -u)" -ne 0 ]]; then
  if ! docker info >/dev/null 2>&1; then
    echo "Docker requires elevated privileges. Enter your password if prompted."
    SUDO="sudo"
    sudo -v || { echo "sudo failed — run this script with a sudoer account."; exit 1; }
  fi
fi

# ── Flags ─────────────────────────────────────────────────────────────────────
NO_PULL=false
SKIP_SERVICE_RESTORES=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --no-pull)               NO_PULL=true ;;
    --skip-service-restores) SKIP_SERVICE_RESTORES=true ;;
    --help|-h)
      echo "Usage: ./restore.sh [--no-pull] [--skip-service-restores]"
      echo "  --no-pull                Skip docker compose pull"
      echo "  --skip-service-restores  Skip Phase-1 sub-restores (if stack already rebuilt)"
      exit 0 ;;
    *) die "Unknown flag: $1" ;;
  esac
  shift
done

bold "🔄 Immich Full Restore"
info "Stack target  : $STACK_DIR"
info "DB dump       : $DUMPFILE"
info "Backed up at  : $BACKED_UP_AT"
line

command -v docker >/dev/null 2>&1      || die "docker not found."
docker compose version >/dev/null 2>&1 || die "docker compose plugin not found."
[[ -f "$DUMPFILE" ]]                   || die "Database dump not found: $DUMPFILE"

run_restore() {
  local script="$1"
  if [[ -f "$script" ]]; then
    info "$(basename "$(dirname "$script")")/restore.sh"
    bash "$script" || warn "Non-zero exit from $script — continuing"
  else
    warn "Not found, skipping: $script"
  fi
}

dc() { $SUDO docker compose -f "$STACK_COMPOSE" --env-file "$STACK_ENV" "$@"; }

RESTOREEOF_MARKER

# Inject the baked service restore lines
cat >> "$RESTORE_SCRIPT" << RESTOREEOF
# ── STEP 1: Restore service compose files and data ────────────────────────────
if [[ "\$SKIP_SERVICE_RESTORES" == true ]]; then
  warn "Skipping service restores (--skip-service-restores)"
else
  bold "STEP 1 — Restoring service compose files and data"
  line
${SERVICE_RESTORE_LINES}
  ok "All service restores complete."
  line
fi
RESTOREEOF

# Final block — back to no-expansion
cat >> "$RESTORE_SCRIPT" << 'RESTOREEOF_MARKER'

[[ -f "$STACK_COMPOSE" ]] || die "compose.yaml missing after service restores: $STACK_COMPOSE"
[[ -f "$STACK_ENV" ]]     || die ".env missing after service restores: $STACK_ENV"

# ── STEP 2: Pull latest images ────────────────────────────────────────────────
if [[ "$NO_PULL" == false ]]; then
  bold "STEP 2 — Pulling latest Immich images"
  line
  dc pull
  ok "Images pulled."
  line
else
  info "Skipping image pull (--no-pull)"
fi

# ── STEP 3: Create containers (not started yet) ───────────────────────────────
bold "STEP 3 — Creating containers (not starting yet)"
line

# Read DB_DATA_LOCATION from the restored stack .env to show a helpful hint
db_data_location="<DB_DATA_LOCATION from $STACK_ENV>"
if [[ -f "$STACK_ENV" ]]; then
  _dbl="$(grep -E '^DB_DATA_LOCATION=' "$STACK_ENV" 2>/dev/null | head -n1 | cut -d= -f2- | tr -d '"' || true)"
  [[ -n "$_dbl" ]] && db_data_location="$_dbl"
fi

warn "If Immich has already run since containers were last created, the DB restore"
warn "will fail with Postgres conflicts. If that happens:"
warn "  1. sudo rm -rf $db_data_location"
warn "  2. Re-run this script"
line

dc down -v 2>/dev/null || true
dc create
ok "Containers created."
line

# ── STEP 4: Start Postgres and wait ──────────────────────────────────────────
bold "STEP 4 — Starting Postgres and waiting for it to be ready"
line
dc start "$POSTGRES_SERVICE"
container_id="$(dc ps -q "$POSTGRES_SERVICE")"
[[ -n "$container_id" ]] || die "Could not find Postgres container after start."

info "Waiting for Postgres to accept connections..."
for i in $(seq 1 30); do
  if $SUDO docker exec "$container_id" pg_isready -U postgres >/dev/null 2>&1; then
    ok "Postgres is ready (attempt $i)."
    break
  fi
  [[ "$i" -eq 30 ]] && die "Postgres did not become ready after 30 seconds."
  sleep 1
done
line

# ── STEP 5: Restore database ──────────────────────────────────────────────────
bold "STEP 5 — Restoring database from pg_dump"
line
info "Source : $DUMPFILE"
info "Method : gunzip | sed (search_path fix) | psql --single-transaction"
line

db_name="immich"
if [[ -f "$STACK_ENV" ]]; then
  _db="$(grep -E '^(DB_DATABASE_NAME|POSTGRES_DB)=' "$STACK_ENV" 2>/dev/null | head -n1 | cut -d= -f2- | tr -d '"' || true)"
  [[ -n "$_db" ]] && db_name="$_db"
fi
info "Database: $db_name"

gunzip --stdout "$DUMPFILE" \
  | sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
  | $SUDO docker exec -i "$container_id" \
      psql --dbname="$db_name" --username=postgres \
           --single-transaction --set ON_ERROR_STOP=on
ok "Database restored."
line

# ── STEP 6: Start full stack ──────────────────────────────────────────────────
bold "STEP 6 — Starting full Immich stack"
line
dc up -d
ok "Immich stack is up."
line

bold "🎉 Immich restore complete!"
echo
info "Next steps:"
info "  1. Open Immich in your browser and verify your library is intact"
info "  2. Missing thumbnails?        Jobs → Generate Thumbnails"
info "  3. Missing transcoded videos? Jobs → Video Transcoding"
echo
RESTOREEOF_MARKER

chmod +x "$RESTORE_SCRIPT"
ok "Master restore.sh written: $RESTORE_SCRIPT"
info "  Baked values:"
info "    POSTGRES_SERVICE : $POSTGRES_SERVICE"
info "    IMMICH_SERVICE   : $IMMICH_SERVICE"
info "    DOCKGE_STACKS_DIR: $DOCKGE_STACKS_DIR"
info "    DB dump expected : $DB_SERVICE_DIR/immich_db.sql.gz"
info "  Embedded service restores:"
for s in "${SERVICE_RESTORE_SCRIPTS[@]}"; do
  info "    ${s#"$CONSOLIDATED_DIR"/}"
done