#!/usr/bin/env bash
# phase-2/tasks/05-write-restore.sh
# Generates a master restore.sh inside the consolidated immich/ output folder.
#
# Inputs (env, all set by orchestrator via STATE_FILE):
#   STATE_FILE, IMMICH_SERVICE, POSTGRES_SERVICE, BACKUP_DIR,
#   DOCKGE_STACKS_DIR, IMMICH_OUT_NAME
#
# Output:
#   $CONSOLIDATED_DIR/restore.sh   (executable)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../../lib/common.sh"

STATE_FILE="${STATE_FILE:?STATE_FILE must be set by the orchestrator}"
[[ -f "$STATE_FILE" ]] || die "State file not found: $STATE_FILE"
# shellcheck source=/dev/null
source "$STATE_FILE"

: "${IMMICH_SERVICE:?}"
: "${POSTGRES_SERVICE:?}"
: "${BACKUP_DIR:?}"

DOCKGE_STACKS_DIR="${DOCKGE_STACKS_DIR:-/opt/stacks}"
IMMICH_OUT_NAME="${IMMICH_OUT_NAME:-immich}"
CONSOLIDATED_DIR="$CENTRAL_BACKUP_DIR/split_stacks/$IMMICH_OUT_NAME"
DB_DUMP_FILE="$BACKUP_DIR/immich_db.sql.gz"

[[ -d "$CONSOLIDATED_DIR" ]] || die \
  "Consolidated dir not found: $CONSOLIDATED_DIR — run 04-consolidate.sh first"
[[ -f "$DB_DUMP_FILE" ]] || die \
  "Database dump not found: $DB_DUMP_FILE — run 02-backup-database.sh first"

RESTORE_SCRIPT="$CONSOLIDATED_DIR/restore.sh"

bold "📝 Writing Immich master restore.sh"
line

# Collect per-service restore.sh scripts Phase 1 generated (now inside immich/<service>/)
mapfile -t SERVICE_RESTORE_SCRIPTS < <(
  find "$CONSOLIDATED_DIR" -mindepth 2 -maxdepth 2 -name "restore.sh" | sort
)

SERVICE_RESTORE_LINES=""
for s in "${SERVICE_RESTORE_SCRIPTS[@]}"; do
  rel="${s#$CONSOLIDATED_DIR/}"
  SERVICE_RESTORE_LINES+="  run_restore \"\$SELF_DIR/$rel\""$'\n'
done

cat > "$RESTORE_SCRIPT" << RESTORE_EOF
#!/usr/bin/env bash
# restore.sh — Immich master restore script
# Generated by phase-2/tasks/05-write-restore.sh
#
# USAGE:  sudo ./restore.sh [--no-pull] [--skip-service-restores]
#
# STEPS:
#   1. Run each service's Phase-1 restore.sh  → rebuilds /opt/stacks/immich
#   2. docker compose pull  (skip with --no-pull)
#   3. docker compose create  (containers created, NOT started)
#   4. Start Postgres only, wait for pg_isready
#   5. Restore pg_dump via gunzip | sed search_path fix | psql --single-transaction
#   6. docker compose up -d  (full stack)
set -euo pipefail

SELF_DIR="\$(cd "\$(dirname "\$0")" && pwd)"

RED="\e[31m"; GREEN="\e[32m"; YELLOW="\e[33m"; BLUE="\e[36m"
BOLD="\e[1m"; RESET="\e[0m"
line()  { echo -e "\${BLUE}------------------------------------------------------------\${RESET}"; }
info()  { echo -e "\${BLUE}\$*\${RESET}"; }
ok()    { echo -e "\${GREEN}✅ \$*\${RESET}"; }
warn()  { echo -e "\${YELLOW}⚠️  \$*\${RESET}"; }
die()   { echo -e "\${RED}❌ \$*\${RESET}" >&2; exit 1; }
bold()  { echo -e "\${BOLD}\$*\${RESET}"; }

# ── Flags ─────────────────────────────────────────────────────────────────────
NO_PULL=false
SKIP_SERVICE_RESTORES=false
while [[ \$# -gt 0 ]]; do
  case "\$1" in
    --no-pull)               NO_PULL=true ;;
    --skip-service-restores) SKIP_SERVICE_RESTORES=true ;;
    --help|-h)
      echo "Usage: sudo ./restore.sh [--no-pull] [--skip-service-restores]"
      echo "  --no-pull                Skip docker compose pull"
      echo "  --skip-service-restores  Skip Phase-1 sub-restores (if /opt/stacks/immich already rebuilt)"
      exit 0 ;;
    *) die "Unknown flag: \$1" ;;
  esac
  shift
done

# ── Baked-in values (set at backup time) ─────────────────────────────────────
DOCKGE_STACKS_DIR="${DOCKGE_STACKS_DIR}"
STACK_DIR="\$DOCKGE_STACKS_DIR/immich"
STACK_COMPOSE="\$STACK_DIR/compose.yaml"
STACK_ENV="\$STACK_DIR/.env"
POSTGRES_SERVICE="${POSTGRES_SERVICE}"
IMMICH_SERVICE="${IMMICH_SERVICE}"
DB_DUMP_FILE="\$SELF_DIR/${POSTGRES_SERVICE}/immich_db.sql.gz"
BACKED_UP_AT="${BACKED_UP_AT:-unknown}"

bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
bold "  Immich Full Restore"
bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
info "  Stack target : \$STACK_DIR"
info "  DB dump      : \$DB_DUMP_FILE"
info "  Backed up at : \$BACKED_UP_AT"
line

command -v docker >/dev/null 2>&1      || die "docker not found."
docker compose version >/dev/null 2>&1 || die "docker compose plugin not found."
[[ -f "\$DB_DUMP_FILE" ]]              || die "Database dump not found: \$DB_DUMP_FILE"

SUDO=""
[[ "\${EUID:-\$(id -u)}" -ne 0 ]] && SUDO=sudo

run_restore() {
  local script="\$1"
  if [[ -f "\$script" ]]; then
    info "  → \$(basename "\$(dirname "\$script")")/restore.sh"
    bash "\$script" || warn "  Non-zero exit from \$script — continuing"
  else
    warn "  Not found, skipping: \$script"
  fi
}

# ── STEP 1 — Restore each service (compose, env, bind-mount data) ─────────────
if [[ "\$SKIP_SERVICE_RESTORES" == true ]]; then
  warn "Skipping service restores (--skip-service-restores)"
else
  bold "➡  STEP 1 — Restoring service compose files and data"
  line
${SERVICE_RESTORE_LINES}
  ok "All service restores complete."
  line
fi

[[ -f "\$STACK_COMPOSE" ]] || die "compose.yaml missing after service restores: \$STACK_COMPOSE"
[[ -f "\$STACK_ENV"     ]] || die ".env missing after service restores: \$STACK_ENV"

# ── STEP 2 — Pull latest images ───────────────────────────────────────────────
if [[ "\$NO_PULL" == false ]]; then
  bold "➡  STEP 2 — Pulling latest Immich images"
  line
  \$SUDO docker compose -f "\$STACK_COMPOSE" --env-file "\$STACK_ENV" pull
  ok "Images pulled."
  line
else
  info "Skipping image pull (--no-pull)"
fi

# ── STEP 3 — Create containers WITHOUT starting them ─────────────────────────
bold "➡  STEP 3 — Creating containers (not starting yet)"
line
warn "If Immich has already run since containers were last created, the DB restore"
warn "will fail with Postgres conflicts. Fix: find DB_DATA_LOCATION in \$STACK_ENV,"
warn "run: sudo rm -rf <DB_DATA_LOCATION>, then re-run this script."
line
\$SUDO docker compose -f "\$STACK_COMPOSE" --env-file "\$STACK_ENV" down -v 2>/dev/null || true
\$SUDO docker compose -f "\$STACK_COMPOSE" --env-file "\$STACK_ENV" create
ok "Containers created."
line

# ── STEP 4 — Start Postgres only and wait for ready ──────────────────────────
bold "➡  STEP 4 — Starting Postgres and waiting for it to be ready"
line
\$SUDO docker compose -f "\$STACK_COMPOSE" --env-file "\$STACK_ENV" start "\$POSTGRES_SERVICE"

postgres_container_id="\$(\$SUDO docker compose -f "\$STACK_COMPOSE" --env-file "\$STACK_ENV" ps -q "\$POSTGRES_SERVICE")"
[[ -n "\$postgres_container_id" ]] || die "Could not find Postgres container after start."

info "Waiting for Postgres to accept connections..."
for i in \$(seq 1 30); do
  if \$SUDO docker exec "\$postgres_container_id" pg_isready -U postgres >/dev/null 2>&1; then
    ok "Postgres is ready (attempt \$i)."
    break
  fi
  [[ \$i -eq 30 ]] && die "Postgres did not become ready after 30 seconds."
  sleep 1
done
line

# ── STEP 5 — Restore the database dump ───────────────────────────────────────
bold "➡  STEP 5 — Restoring database from pg_dump"
line
info "  Source : \$DB_DUMP_FILE"
info "  Method : gunzip | sed search_path fix | psql --single-transaction"
line

# Detect db name from the restored stack .env, fall back to 'immich'
db_name="immich"
if [[ -f "\$STACK_ENV" ]]; then
  _db="\$(grep -E '^(DB_DATABASE_NAME|POSTGRES_DB)=' "\$STACK_ENV" 2>/dev/null \
        | head -n1 | cut -d= -f2- | tr -d '\"' || true)"
  [[ -n "\$_db" ]] && db_name="\$_db"
fi
info "  Database: \$db_name"

gunzip --stdout "\$DB_DUMP_FILE" \
  | sed "s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g" \
  | \$SUDO docker exec -i "\$postgres_container_id" \
      psql \
        --dbname="\$db_name" \
        --username=postgres \
        --single-transaction \
        --set ON_ERROR_STOP=on

ok "Database restored."
line

# ── STEP 6 — Start the full stack ────────────────────────────────────────────
bold "➡  STEP 6 — Starting full Immich stack"
line
\$SUDO docker compose -f "\$STACK_COMPOSE" --env-file "\$STACK_ENV" up -d
ok "Immich stack is up."
line

bold "🎉 Immich restore complete!"
echo ""
info "  Next steps:"
info "  1. Open Immich in your browser and verify your library is intact"
info "  2. Missing thumbnails? Jobs → Generate Thumbnails"
info "  3. Missing transcoded videos? Jobs → Video Transcoding"
echo ""
RESTORE_EOF

chmod +x "$RESTORE_SCRIPT"
ok "Master restore.sh written: $RESTORE_SCRIPT"
info "  Baked values:"
info "    POSTGRES_SERVICE : $POSTGRES_SERVICE"
info "    IMMICH_SERVICE   : $IMMICH_SERVICE"
info "    DOCKGE_STACKS_DIR: $DOCKGE_STACKS_DIR"
info "    DB dump expected : ./${POSTGRES_SERVICE}/immich_db.sql.gz"
info "  Embedded service restores:"
for s in "${SERVICE_RESTORE_SCRIPTS[@]}"; do
  info "    ${s#$CONSOLIDATED_DIR/}"
done